CREATE TABLE LANGUAGE(
lANGUAGE_id Numeric primary key,
Name varchar(20) not null
);

CREATE TABLE PUBLISHER(
PUBLISHER_ID NUMERIC PRIMARY KEY,
NAME VARCHAR(20) NOT NULL
);


CREATE TABLE BOOK(
BOOK_ID NUMERIC PRIMARY KEY,
TITLE VARCHAR(20) NOT NULL,
LANGUAGE_ID NUMERIC, 
MRP NUMERIC,
PUBLISHER_ID NUMERIC,
PUBLISHED_DATE DATE,
VOLUME NUMERIC,
STATUS VARCHAR(20),
FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE,
FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER);

CREATE TABLE AUTHOR(
AUTHOR_ID NUMERIC PRIMARY KEY,
NAME VARCHAR(20) NOT NULL,
EMAIL VARCHAR(50),
PHONE_NUMBER NUMERIC,
STATUS VARCHAR(20)
);

CREATE TABLE BOOK_AUTHOR(
BOOK_ID NUMERIC,
AUTHOR_ID NUMERIC,
PRIMARY KEY(BOOK_ID,AUTHOR_ID),
FOREIGN KEY (BOOK_ID) REFERENCES BOOK,
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR
);

