--DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE(
EMP_ID VARCHAR(20) PRIMARY KEY,
EMP_NAME VARCHAR(36),
DEPT VARCHAR(36),
SALARY NUMBER(10)
);

INSERT ALL
INTO EMPLOYEE VALUES('2E1','DAVID SMITH','HR',2000)
INTO EMPLOYEE VALUES('2E2','OMANA SMITH','PRDOUCTION',5000)
INTO EMPLOYEE VALUES('2E3','CHARLES BABBAGE','SALES',8000)
INTO EMPLOYEE VALUES('2E4','ALEXANDER FLEMING','MARKETING',10000)
INTO EMPLOYEE VALUES('2E5','CRISTIANO RONALOD','HR',2000)
SELECT * FROM DUAL;

SELECT * FROM EMPLOYEE WHERE SALARY>7000;
SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET SALARY=8200 WHERE EMP_NAME='DAVID SMITH';
SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPT='PRODUCTION' WHERE DEPT='PRDOUCTION';
SELECT * FROM EMPLOYEE;

INSERT INTO EMPLOYEE VALUES('6','DANIEL HARRIS','PRODUCTION0',6700);
SELECT * FROM EMPLOYEE;
INSERT INTO EMPLOYEE VALUES('3','DONALD TRUMP','MARKETING',9700);
SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE WHERE EMP_ID='3';
SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE EMP_NAME NOT LIKE 'D%' AND EMP_NAME NOT LIKE 'O%';
UPDATE EMPLOYEE SET DEPT='PRODUCTION' WHERE DEPT='PRODUCTIONO';
SELECT * FROM EMPLOYEE;


